framework:
    messenger:
        failure_transport: failed

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # El envio de emails de dorsales se realiza sincronamente desde el comando CLI.
            # App\Application\Results\ImportResults\ImportResultsCommand: async
            # App\Application\Media\GenerateThumbnail\GenerateThumbnailCommand: async
            # App\Application\Notification\SendEmail\SendEmailCommand: async
