<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260524202809 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE blog_posts (id UUID NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, excerpt TEXT NOT NULL, content TEXT NOT NULL, tag VARCHAR(50) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cover_image VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_78B2F932989D9B62 ON blog_posts (slug)');
        $this->addSql('CREATE TABLE categories (id VARCHAR(36) NOT NULL, name VARCHAR(255) NOT NULL, min_age INT DEFAULT NULL, max_age INT DEFAULT NULL, distance_km DOUBLE PRECISION NOT NULL, gender VARCHAR(1) DEFAULT NULL, race_edition_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AF3466817F7F0C7 ON categories (race_edition_id)');
        $this->addSql('CREATE TABLE photos (id VARCHAR(36) NOT NULL, filename VARCHAR(255) NOT NULL, thumbnail_filename VARCHAR(255) DEFAULT NULL, caption VARCHAR(255) DEFAULT NULL, is_featured BOOLEAN NOT NULL, sort_order INT NOT NULL, race_edition_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_876E0D917F7F0C7 ON photos (race_edition_id)');
        $this->addSql('CREATE TABLE race_editions (id UUID NOT NULL, year SMALLINT NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, poster_url VARCHAR(255) DEFAULT NULL, registration_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE results (id VARCHAR(36) NOT NULL, bib_number VARCHAR(20) NOT NULL, finish_time_seconds INT NOT NULL, position INT DEFAULT NULL, gender_position INT DEFAULT NULL, category_position INT DEFAULT NULL, race_edition_id UUID NOT NULL, runner_id UUID NOT NULL, category_id VARCHAR(36) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9FA3E4143C7FB593 ON results (runner_id)');
        $this->addSql('CREATE INDEX IDX_9FA3E41412469DE2 ON results (category_id)');
        $this->addSql('CREATE INDEX idx_result_edition ON results (race_edition_id)');
        $this->addSql('CREATE TABLE runners (id UUID NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, club VARCHAR(255) DEFAULT NULL, birth_date DATE DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE sponsors (id VARCHAR(36) NOT NULL, name VARCHAR(255) NOT NULL, logo_url VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, tier VARCHAR(20) NOT NULL, is_active BOOLEAN NOT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "users" (id VARCHAR(36) NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "users" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF3466817F7F0C7 FOREIGN KEY (race_edition_id) REFERENCES race_editions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photos ADD CONSTRAINT FK_876E0D917F7F0C7 FOREIGN KEY (race_edition_id) REFERENCES race_editions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE results ADD CONSTRAINT FK_9FA3E41417F7F0C7 FOREIGN KEY (race_edition_id) REFERENCES race_editions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE results ADD CONSTRAINT FK_9FA3E4143C7FB593 FOREIGN KEY (runner_id) REFERENCES runners (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE results ADD CONSTRAINT FK_9FA3E41412469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT FK_3AF3466817F7F0C7');
        $this->addSql('ALTER TABLE photos DROP CONSTRAINT FK_876E0D917F7F0C7');
        $this->addSql('ALTER TABLE results DROP CONSTRAINT FK_9FA3E41417F7F0C7');
        $this->addSql('ALTER TABLE results DROP CONSTRAINT FK_9FA3E4143C7FB593');
        $this->addSql('ALTER TABLE results DROP CONSTRAINT FK_9FA3E41412469DE2');
        $this->addSql('DROP TABLE blog_posts');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE photos');
        $this->addSql('DROP TABLE race_editions');
        $this->addSql('DROP TABLE results');
        $this->addSql('DROP TABLE runners');
        $this->addSql('DROP TABLE sponsors');
        $this->addSql('DROP TABLE "users"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
